version: '3.0'
services:
 alphadev:
  build: .
  environment:
   - NODE_ENV=production
  container_name: alphadev
  restart: unless-stopped
  networks:
   - app-network
 webserver:
  image: nginx:mainline-alpine
  container_name: webserver
  restart: unless-stopped
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - web-root:/var/www/html
   - ./nginx-conf:/etc/nginx/conf.d
   - certbot-etc:/etc/letsencrypt
   - certbot-var:/var/lib/letsencrypt
   - dhparam:/etc/ssl/certs
  depends_on:
   - alphadev
  networks:
   - app-network
 certbot:
  image: certbot/certbot
  container_name: certbot
  volumes:
   - certbot-etc:/etc/letsencrypt
   - certbot-var:/var/lib/letsencrypt
   - web-root:/var/www/html
  depends_on:
   - webserver
  command: certonly --webroot --webroot-path=/var/www/html --email cyrilcabo@gmail.com --agree-tos --no-eff-email --force-renewal -d alphadevop.co  -d www.alphadevop.co
volumes:
 certbot-etc:
 certbot-var:
 web-root:
  driver: local
  driver_opts:
   type: none
   device: /home/ubuntu/alphadevelopment/server/build
   o: bind
 dhparam:
  driver: local
  driver_opts:
   type: none
   device: /home/ubuntu/alphadevelopment/dhparam/
   o: bind
networks:
 app-network:
  driver: bridge
